### PR TITLE
feat: Correct Serialization of google::protobuf::*Value Types

### PR DESCRIPTION
**Pull request by rise0chen**
Warn: BytesValue can't work

### CODE REVIEW

**Review by tustvold — APPROVED** [review]
Looks good to me, what was the reason for not adding ByteArray?

**Comment by rise0chen** [comment]
BytesValue contain `prost::bytes::Bytes`, It can't serializa

**Comment by tustvold** [comment]
We have working plumbing for serializing bytes - https://github.com/influxdata/pbjson/blob/main/pbjson-test/protos/syntax3.proto#L75

In particular

* https://github.com/influxdata/pbjson/blob/main/pbjson/src/lib.rs#L57
* https://github.com/influxdata/pbjson/blob/main/pbjson-build/src/generator/message.rs#L272
* https://github.com/influxdata/pbjson/blob/main/pbjson-build/src/generator/message.rs#L818

**Comment by tustvold** [comment]
I'm going to get this in, thank you :+1:

Feel free to open a follow up PR to add BytesValue support if you would like to :smile:

**Pull request merged**
