### PR TITLE
Update Rust toolchain to 1.56.1 and 2021 edition

### PR DESCRIPTION
**Pull request by XAMPPRocky**
This PR updates the crates in the repository to use the latest version and edition.

### CODE REVIEW

**Comment by tustvold** [comment]
Thank you for this :heart: 

I just need you to please sign the [CLA](https://www.influxdata.com/legal/cla/), and then I'll be happy to get this in :smile:

I'll take a look at #16 shortly

**Comment by XAMPPRocky** [comment]
Hmm, I would normally not have a problem signing a CLA, however your CLA requires too much personal information (namely a phone number or Skype username), that I'm not willing to give. If this was removed or made not required, I would be happy to sign it, otherwise we can close these, and I'll find an alternative solution.

**Comment by e-dard** [comment]
Hey there @XAMPPRocky, thanks so much for you contribution to this project.  The CLA, which can be in the link @tustvold posted above only requires you Github username, email contact and a name. This information is not made public.

Whilst the CLA is a bit of a hoop that needs to be jumped through, it protects both contributors and InfluxData, and allows us to open-source much of the work that goes on within the company.

**Comment by XAMPPRocky** [comment]
@e-dard Thank you for updating it, when I looked at on Saturday it definitely was required in the form. I've now signed the CLA so these should be good to review.

**Comment by e-dard** [comment]
@XAMPPRocky oh great - I didn't realise it had become required at some point. Glad it's fixed and you can proceed 👍

**Review by tustvold — APPROVED** [review]

**Pull request merged**
